### ISSUE TITLE
SiMAYA-L: Node kres setelah sinkron surat

### ISSUE THREAD

**Issue by dotovr** [simaya/simaya#233]
Tahap Awal :  
* Buat titik sambungan
* Sinkron data pertama kali

Node kres di siMAYA Lokal saat login setelah sinkron data surat dari siMAYA Master
Skenario:
siMAYA Master (Pengirim surat)
* Login sebagai `bupati.bimtek` buat surat atas namanya sendiri
* Login sebagai `tu.bupati` untuk mengirim surat ke penerima

siMAYA Lokal (Penerima surat)
* Login sebagai `admin.global`, buka menu `siMAYA-L > Permintaan Sambungan` 
* Lakukan sinkronisasi, setelah selesai sinkron
* Logout `admin.global`, lanjut login sebagai akun lain (`tu.selatan`)
* Node jadi kres saat login (terjadi untuk semua akun yang dibuat di lokal)
Log : 
```sh
GET /login 304 64ms
ub766d1b5-34e1-430d-bf8e-5253d69628f1:tu.selatan

/home/vagrant/simaya/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
Error: data and hash arguments required
    at Object.module.exports.compareSync (/home/vagrant/simaya/node_modules/bcrypt/bcrypt.js:109:15)
    at /home/vagrant/simaya/sinergis-base/sinergis/models/user.js:334:27
    at /home/vagrant/simaya/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at Cursor.nextObject (/home/vagrant/simaya/node_modules/mongodb/lib/mongodb/cursor.js:753:5)
    at commandHandler (/home/vagrant/simaya/node_modules/mongodb/lib/mongodb/cursor.js:727:14)
    at /home/vagrant/simaya/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/home/vagrant/simaya/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /home/vagrant/simaya/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/home/vagrant/simaya/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/vagrant/simaya/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)

```

**Comment by dotovr** [comment]
Terima kasih pak
