### ISSUE TITLE
Gateway Time Out pada saat assign admin lokal ke instansi dari admin root

### ISSUE THREAD

**Issue by dirr** [simaya/simaya#289]
Admin Root membuat username dan ingin meng edit meletakkan ke instansi tertentu.. Pada saat di klil tombol simpan dan tutup akan bad gateway
![screen shot 2015-01-12 at 1 50 36 pm](https://cloud.githubusercontent.com/assets/8622097/5699754/0e1a0b3a-9a62-11e4-9d02-759e3174bdb7.png)
![screen shot 2015-01-12 at 1 48 38 pm](https://cloud.githubusercontent.com/assets/8622097/5699756/168b3d8e-9a62-11e4-9065-f7542e240d05.png)

**Comment by dotovr** [comment]
Lognya:

```sh
/home/$USER/simaya-v4/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/home/$USER/simaya-v4/node_modules/express/node_modules/connect/lib/patch.js:63:22)
    at ServerResponse.res.set.res.header (/home/$USER/simaya-v4/node_modules/express/lib/response.js:527:10)
    at ServerResponse.res.location (/home/$USER/simaya-v4/node_modules/express/lib/response.js:657:8)
    at ServerResponse.res.redirect (/home/$USER/simaya-v4/node_modules/express/lib/response.js:698:8)
    at /home/$USER/simaya-v4/sinergis-base/sinergis/controller/utils.js:119:15
    at /home/$USER/simaya-v4/sinergis-base/sinergis/models/session.js:242:13
    at /home/$USER/simaya-v4/node_modules/mongolia/lib/helpers/collection_proxy.js:153:7
    at Object.MODEL.afterRemove (/home/$USER/simaya-v4/node_modules/mongolia/lib/model.js:217:5)
    at args.(anonymous function) (/home/$USER/simaya-v4/node_modules/mongolia/lib/helpers/collection_proxy.js:152:11)
```

**Comment by dotovr** [comment]
Terima kasih pak
