### ISSUE TITLE
TIDAK BISA MENJALANKAN SIMAYA@4.0

### ISSUE THREAD

**Issue by dygithub88** [simaya/simaya#321]
npm WARN package.json simaya@4.0.0 No repository field.
npm WARN package.json file-preview@0.0.6 No repository field.
npm WARN cannot run in wd simaya@4.0.0 make setup (wd=/root/simaya)
pdfinfo@0.0.3 node_modules/pdfinfo

**Comment by dygithub88** [comment]
SAAT INSTALL MENGGUNAKAN "npm -d install" 

npm WARN package.json simaya@4.0.0 No repository field.
npm WARN package.json file-preview@0.0.6 No repository field.
npm WARN cannot run in wd simaya@4.0.0 make setup (wd=/root/simaya)
pdfinfo@0.0.3 node_modules/pdfinfo

45:~/simaya# node app.js

/root/simaya/settings.js:9
    , ObjectID = db.bson_serializer.ObjectID
                                   ^
TypeError: Cannot read property 'ObjectID' of undefined
    at /root/simaya/settings.js:9:36
    at Object.<anonymous> (/root/simaya/settings.js:60:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/simaya/app.js:5:16)
    at Module._compile (module.js:456:26)
